name: Latest release

on:
  push:
    branches:
      - 'main'
        
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace }}/nuget
  NuGetSource: https://api.nuget.org/v3/index.json
    
jobs:       
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        
      - name: Run unit tests
        run: dotnet test SimpleFluentTester.UnitTests -c Release 
          /p:CollectCoverage=true 
          /p:CoverletOutput=TestResults/ 
          /p:CoverletOutputFormat=lcov

      - name: Publish coverage report to coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: SimpleFluentTester.UnitTests/TestResults/coverage.info
  
  create_nuget:
    runs-on: ubuntu-latest
    needs: [ unit_tests ]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
      
      - run: dotnet pack SimpleFluentTester.Core -c Release -o ${{ env.NuGetDirectory }}

      - name: Upload nuget artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget
          if-no-files-found: error
          retention-days: 7
          path: ${{ env.NuGetDirectory }}/SimpleFluentTester.*.nupkg

  deploy_nuget:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs: [ create_nuget ]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: nuget
          path: ${{ env.NuGetDirectory }}

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
          
      - name: Publish NuGet package to NuGet Packages
        run: |
          dotnet nuget push ${{ env.NuGetDirectory }}/SimpleFluentTester.*.nupkg -k "${{ secrets.NUGET_TOKEN }}" -s ${{ env.NuGetSource }} --skip-duplicate