name: Latest release

on:
  push:
    branches:
      - 'main'
        
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace }}/nuget
  NuGetSource: https://api.nuget.org/v3/index.json
    
jobs:       
  unit_tests:
    uses: ./.github/workflows/reusable/reusable_unit_tests.yml

  deploy_main_nuget:
    uses: ./.github/workflows/reusable/reusable_deploy_nuget.yml
    with:
      project-name: SimpleFluentTester
      version-fragment: 'feature'
      nuget-name: 'simplefluenttester'