name: Latest release

on:
  push:
    branches:
      - 'main'
    
jobs:       
  unit_tests:
    uses: ./.github/workflows/unit_tests.yml

  deploy_main_nuget:
    uses: ./.github/workflows/deploy_nuget.yml
    needs: [ unit_tests ]
    with:
      project-name: SimpleFluentTester
      version-fragment: 'feature'
      nuget-name: 'simplefluenttester'
    secrets:
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
      
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Prerelease Branch with Main
        uses: remarkablemark/sync-branch@v1
        with:
          base: prerelease
          token: ${{ secrets.GITHUB_TOKEN }}
