on:
  push:
    branches:
      - 'master'
        
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace }}/nuget
  NuGetSource: https://nuget.pkg.github.com/abatar1/index.json
    
jobs:       
  run_test:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        
      - name: Run unit tests
        run: dotnet test SimpleFluentTester.UnitTests -c Release
        
  create_nuget:
    runs-on: ubuntu-latest
    needs: [ run_test ]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: bin-core
          path: ${{ env.BinDirectory }}
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
      
      - run: dotnet pack SimpleFluentTester.Core -c Release -o ${{ env.NuGetDirectory }}

      - name: Upload nuget artifact
        uses: actions/upload-artifact@v3
        with:
          name: nuget
          if-no-files-found: error
          retention-days: 7
          path: ${{ env.NuGetDirectory }}/SimpleFluentTester.*.nupkg

  deploy_nuget:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs: [ create_nuget ]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: nuget
          path: ${{ env.NuGetDirectory }}

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4

      - name: Publish NuGet package
        run: |
          dotnet nuget push ${{ env.NuGetDirectory }}/SimpleFluentTester.*.nupkg -k "${{ secrets.GITHUB_TOKEN }}" -s ${{ env.NuGetSource }} --skip-duplicate