on:
  push:
    branches:
      - 'master'
        
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace }}/nuget
  BinDirectory: ${{ github.workspace }}/bin
  NuGetPackageName: SimpleFluentTester
  NuGetSource: https://nuget.pkg.github.com/abatar1/index.json
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        
      - name: Build
        run: dotnet build --configuration Release --output ${{ env.BinDirectory }}
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: bin
          if-no-files-found: error
          retention-days: 7
          path: ${{ env.BinDirectory }}
        
  run_test:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: bin
          path: ${{ env.BinDirectory }}
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        
      - name: Run unit tests
        run: dotnet test ${{ env.BinDirectory }}/{{ env.NuGetPackageName }}.UnitTests.dll --no-build
        
  create_nuget:
    runs-on: ubuntu-latest
    needs: [ run_test ]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: bin
          path: ${{ env.BinDirectory }}
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
      
      - run: dotnet pack ${{ env.BinDirectory }}/${{ env.NuGetPackageName }}.Core.dll --output ${{ env.NuGetDirectory }} --no-build

      - name: Upload nuget artifact
        uses: actions/upload-artifact@v3
        with:
          name: nuget
          if-no-files-found: error
          retention-days: 7
          path: ${{ env.NuGetDirectory }}/${{ env.NuGetPackageName }}.*.nupkg

  deploy_nuget:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs: [ create_nuget ]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: nuget
          path: ${{ env.NuGetDirectory }}

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4

      - name: Publish NuGet package
        run: |
          dotnet nuget push ${{ env.NuGetDirectory }}/${{ env.NuGetPackageName }}.*.nupkg --api-key "${{ secrets.GITHUB_TOKEN }}" --source ${{ env.NuGetSource }} --skip-duplicate