name: 'Pull Request'

on:
  pull_request:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'main' && github.head_ref != 'prerelease'
        run: |
          echo "ERROR: You can only merge to main from prerelease branch."
          exit 1
          
  unit_tests:
    uses: ./.github/workflows/reusable/reusable_unit_tests.yml