name: 'Pull Request'

on:
  pull_request:
    paths:
      - "**.cs"
      - "**.csproj"

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'main' && github.head_ref != 'prerelease'
        run: |
          echo "ERROR: You can only merge to main from prerelease branch."
          exit 1
          
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Run unit tests
        run: dotnet test SimpleFluentTester.UnitTests -c Release
          /p:CollectCoverage=true
          /p:CoverletOutput=TestResults/
          /p:CoverletOutputFormat=lcov

      - name: Publish coverage report to coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: SimpleFluentTester.UnitTests/TestResults/coverage.info
          flag-name: pr