name: Prerelease

on:
  push:
    branches:
      - 'prerelease'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace }}/nuget
  NuGetSource: https://api.nuget.org/v3/index.json

jobs:
  unit_tests:
    uses: ./.github/workflows/unit_tests.yml
    
  deploy_main_nuget:
    uses: ./.github/workflows/deploy_nuget.yml
    needs: [ unit_tests ]
    with:
      project-name: SimpleFluentTester
      version-fragment: 'bug'
      nuget-name: 'simplefluenttester'